version: 2
jobs:
  build:
    working_directory: ~/featuretools
    docker:
        - image: themattrix/tox
    steps:
      - run: apt update && apt install git -y
      - checkout
      - run: pyenv local 2.7.13 3.5.2 3.6.0
      - run: make installdeps
      - run: tox && make lint && codecov
