version: 2
jobs:
  build:
    working_directory: ~/featuretools
    docker:
        - image: themattrix/tox
    steps:
      - checkout
      - run: pyenv local 2.7 3.5 3.6
      - run: make installdeps
      - run: tox && make lint && codecov
